language: php

sudo: false

cache:
    directories:
        - bin
        - vendor
php:
  - 5.6
  - 7.0
  - 7.1

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer install -n

before_script:
    - composer validate
    - bin/console doctrine:database:create -vvv
    - bin/console doctrine:schema:create -vvv

script: bin/phpunit
